name: Security Scan (SAST)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeql-scan:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Executar análise CodeQL
        uses: github/codeql-action/analyze@v3

  semgrep-scan:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: sudo apt update && sudo apt install -y python3-pip

      - name: Instalar Semgrep
        run: pip install --upgrade semgrep

      - name: Rodar Semgrep (Java e .NET)
        run: semgrep --config=auto --error

  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - name: Verificar se Trivy foi instalado corretamente
        run: trivy --version

      - name: Rodar Trivy no código-fonte
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
