name: Security Scan (SAST)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  codeql-scan:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verificar estrutura do repositório
        run: ls -la

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Baixar dependência do Servlet (javax.servlet-api)
        run: |
          mkdir -p libs
          wget https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.jar -P libs/

      - name: Configurar CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          setup: true
          queries: +security-and-quality

      - name: Detectar ferramenta de build e compilar
        run: |
          if [ -f "pom.xml" ]; then
            echo "Maven detectado. Executando mvn clean install..."
            mvn clean install -DskipTests
          elif [ -f "build.gradle" ] || [ -f "settings.gradle" ]; then
            echo "Gradle detectado. Executando ./gradlew build..."
            chmod +x gradlew
            ./gradlew build -x test
          elif ls *.java 1> /dev/null 2>&1; then
            echo "Java puro detectado. Compilando com javac..."
            mkdir -p bin
            find . -name "*.java" > sources.txt
            javac -cp libs/javax.servlet-api-4.0.1.jar:. -d bin @sources.txt
          else
            echo "Nenhuma ferramenta de build detectada."
            exit 1
          fi

      - name: Autodetectar código para CodeQL
        run: |
          codeql database trace-command -- dbcompile javac -cp libs/javax.servlet-api-4.0.1.jar -d bin @sources.txt

      - name: Rodar análise CodeQL
        uses: github/codeql-action/analyze@v3

  semgrep-scan:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar pip
        run: sudo apt-get install -y python3-pip

      - name: Atualizar pip
        run: pip install --upgrade pip

      - name: Instalar Semgrep
        run: pip install --upgrade semgrep

      - name: Verificar instalação do Semgrep
        run: semgrep --version

      - name: Rodar Semgrep
        run: semgrep --config=auto --exclude '**/.git/**' --verbose

  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          TRIVY_VERSION="0.48.2"
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          tar -xzf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Verificar instalação do Trivy
        run: trivy --version

      - name: Rodar Trivy no código-fonte
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
