name: Semgrep Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  semgrep-scan:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar e atualizar Semgrep
        run: |
          pip install --upgrade semgrep

      - name: Verificar instalação do Semgrep
        run: semgrep --version

      - name: Rodar Semgrep com regras de segurança
        run: semgrep --config=p/ci --exclude '**/.git/**' --verbose
